CREATE TABLE termin_template (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    day_of_week VARCHAR(10) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    status SMALLINT NOT NULL DEFAULT 1,
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT chk_termin_template_status CHECK (status IN (0, 1, 2, 3)),
    CONSTRAINT chk_termin_template_time_order CHECK (end_time > start_time)
);

ALTER TABLE termin ADD COLUMN template_id BIGINT NULL REFERENCES termin_template(id);
