CREATE TABLE appointment_reminder (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    appointment_id BIGINT NOT NULL,
    type VARCHAR(20) NOT NULL,
    scheduled_at TIMESTAMP NOT NULL,
    sent_at TIMESTAMP,
    CONSTRAINT fk_appointment_reminder_appointment FOREIGN KEY (appointment_id) REFERENCES appointment (id) ON DELETE CASCADE,
    CONSTRAINT chk_appointment_reminder_type CHECK (type IN ('DAY_BEFORE', 'HOUR_BEFORE'))
);
