CREATE TABLE pilates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    position VARCHAR(50) NOT NULL,
    name VARCHAR(120) NOT NULL,
    status SMALLINT NOT NULL DEFAULT 1,
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT chk_pilates_status CHECK (status IN (0, 1, 2, 3))
);
