CREATE TABLE appointment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    termin_id BIGINT NOT NULL,
    pilates_id BIGINT NOT NULL,
    user_id BIGINT,
    status VARCHAR(20) NOT NULL DEFAULT 'AVAILABLE',
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT fk_appointment_termin FOREIGN KEY (termin_id) REFERENCES termin (id),
    CONSTRAINT fk_appointment_pilates FOREIGN KEY (pilates_id) REFERENCES pilates (id),
    CONSTRAINT fk_appointment_user FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT uk_appointment_termin_pilates UNIQUE (termin_id, pilates_id),
    CONSTRAINT chk_appointment_status CHECK (status IN ('AVAILABLE', 'BOOKED', 'CANCELED'))
);
